version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: multimodal-elasticsearch
    environment:
    - discovery.type=single-node
    - ES_JAVA_OPTS=-Xms2g -Xmx2g
    - xpack.security.enabled=false
    - xpack.security.enrollment.enabled=false
    volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data
    - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
    - 9200:9200
    - 9300:9300
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:9200/_cluster/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
    - multimodal-net
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: multimodal-logstash
    environment:
    - LS_JAVA_OPTS=-Xms1g -Xmx1g
    - PIPELINE_WORKERS=4
    - PIPELINE_BATCH_SIZE=1000
    - PIPELINE_BATCH_DELAY=50
    volumes:
    - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /var/log/multimodal:/var/log/multimodal:ro
    ports:
    - 5044:5044
    - 514:514/udp
    depends_on:
    - elasticsearch
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:9600/_node/stats || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
    - multimodal-net
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: multimodal-kibana
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - xpack.security.enabled=false
    volumes:
    - ./configs/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:5601/api/status || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
    - multimodal-net
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: multimodal-filebeat
    user: root
    volumes:
    - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /var/log/multimodal:/var/log/multimodal:ro
    depends_on:
    - logstash
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    restart: unless-stopped
    networks:
    - multimodal-net
volumes:
  elasticsearch_data:
    driver: local
