# Allure Framework Docker Setup
# Generated on: 2025-09-29T10:27:54.022277

version: '3.8'

services:
  # Allure Results Server
  allure-results:
    image: frankescobar/allure-docker-service:latest
    container_name: multimodal-allure-results
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY=1
      - KEEP_HISTORY_BY_DAYS=30
      - CLEAN_RESULTS_DIRECTORY=1
    volumes:
      - allure_results:/app/allure-results
      - allure_history:/app/default-reports
    ports:
      - "5050:5050"
    restart: unless-stopped
    networks:
      - multimodal-net

  # Allure Report Server
  allure-report:
    image: frankescobar/allure-docker-service:latest
    container_name: multimodal-allure-report
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY=1
      - KEEP_HISTORY_BY_DAYS=30
      - CLEAN_RESULTS_DIRECTORY=1
    volumes:
      - allure_results:/app/allure-results
      - allure_history:/app/default-reports
    ports:
      - "8080:5050"
    restart: unless-stopped
    networks:
      - multimodal-net

  # Allure CLI for report generation
  allure-cli:
    image: frankescobar/allure-docker-service:latest
    container_name: multimodal-allure-cli
    volumes:
      - allure_results:/app/allure-results
      - allure_history:/app/default-reports
      - ./reports:/app/reports
    command: >
      sh -c "
        allure generate /app/allure-results -o /app/reports/allure-report --clean &&
        allure open /app/reports/allure-report --port 8080 --host 0.0.0.0
      "
    ports:
      - "8081:8080"
    depends_on:
      - allure-results
    restart: unless-stopped
    networks:
      - multimodal-net

volumes:
  allure_results:
  allure_history:

networks:
  multimodal-net:
    external: true
