# AI Agents Service Docker Compose
version: '3.8'

services:
  # AI Agents Service
  ai-agents:
    build:
      context: ./services/ai-agents
      dockerfile: Dockerfile
    container_name: multimodal-ai-agents
    ports:
      - "8003:8003"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=multimodal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - MULTIMODAL_WORKER_URL=http://multimodal-worker:8001
      - RETRIEVAL_PROXY_URL=http://retrieval-proxy:8002
      - LLM_BASE_URL=http://vllm:8000/v1
      - LLM_MODEL=microsoft/DialoGPT-medium
    depends_on:
      - postgres
      - qdrant
      - multimodal-worker
      - retrieval-proxy
      - vllm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - multimodal-net

  # AI Agents Web Interface
  ai-agents-web:
    build:
      context: ./services/ai-agents/web
      dockerfile: Dockerfile
    container_name: multimodal-ai-agents-web
    ports:
      - "3001:3000"
    depends_on:
      - ai-agents
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - multimodal-net

networks:
  multimodal-net:
    external: true

volumes:
  postgres_data:
    external: true
  qdrant_data:
    external: true
  minio_data:
    external: true
