# JMeter Performance Testing Docker Setup
# Generated on: 2025-09-29T10:35:41.255917

version: '3.8'

services:
  # JMeter Master
  jmeter-master:
    image: justb4/jmeter:5.6.2
    container_name: multimodal-jmeter-master
    environment:
      - JMETER_HEAP=-Xms2g -Xmx4g
    volumes:
      - ./jmeter:/tests
      - ./jmeter-results:/results
      - ./jmeter-reports:/reports
    command: >
      sh -c "
        jmeter -n -t /tests/api_load_test.jmx -l /results/api_load_test_results.jtl -e -o /reports/api_load_test_report &&
        jmeter -n -t /tests/stress_test.jmx -l /results/stress_test_results.jtl -e -o /reports/stress_test_report &&
        jmeter -n -t /tests/spike_test.jmx -l /results/spike_test_results.jtl -e -o /reports/spike_test_report
      "
    networks:
      - multimodal-net

  # JMeter Results Server
  jmeter-results:
    image: nginx:alpine
    container_name: multimodal-jmeter-results
    ports:
      - "8080:80"
    volumes:
      - ./jmeter-reports:/usr/share/nginx/html:ro
    networks:
      - multimodal-net

volumes:
  jmeter_results:
  jmeter_reports:

networks:
  multimodal-net:
    external: true
