# Docker Compose Override for DEVELOPMENT
services:
  postgres:
    env_file:
      - .env.development
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}

  redis:
    env_file:
      - .env.development
    environment:
      - REDIS_PORT=${REDIS_PORT}

  qdrant:
    env_file:
      - .env.development
    environment:
      - QDRANT_HTTP_PORT=${QDRANT_HTTP_PORT}
      - QDRANT_GRPC_PORT=${QDRANT_GRPC_PORT}

  minio:
    env_file:
      - .env.development
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}

  vllm:
    env_file:
      - .env.development
    environment:
      - VLLM_MODEL=${VLLM_MODEL}
      - VLLM_API_KEY=${VLLM_API_KEY}
      - VLLM_HOST=${VLLM_HOST}
      - VLLM_PORT=${VLLM_PORT}
      - VLLM_GPU_MEMORY_UTILIZATION=${VLLM_GPU_MEMORY_UTILIZATION}
      - VLLM_MAX_MODEL_LEN=${VLLM_MAX_MODEL_LEN}

  litellm:
    env_file:
      - .env.development
    environment:
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - LITELLM_SALT_KEY=${LITELLM_SALT_KEY}
      - LITELLM_PORT=${LITELLM_PORT}

  multimodal-worker:
    env_file:
      - .env.development
    environment:
      - MULTIMODAL_WORKER_PORT=${MULTIMODAL_WORKER_PORT}

  retrieval-proxy:
    env_file:
      - .env.development
    environment:
      - RETRIEVAL_PROXY_PORT=${RETRIEVAL_PROXY_PORT}

  ai-agents:
    env_file:
      - .env.development
    environment:
      - AI_AGENTS_PORT=${AI_AGENTS_PORT}

  search-engine:
    env_file:
      - .env.development
    environment:
      - SEARCH_ENGINE_PORT=${SEARCH_ENGINE_PORT}

  memory-system:
    env_file:
      - .env.development
    environment:
      - MEMORY_SYSTEM_PORT=${MEMORY_SYSTEM_PORT}

  user-management:
    env_file:
      - .env.development
    environment:
      - USER_MANAGEMENT_PORT=${USER_MANAGEMENT_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  openwebui:
    env_file:
      - .env.development
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - OPENWEBUI_PORT=${OPENWEBUI_PORT}

  n8n:
    env_file:
      - .env.development
    environment:
      - N8N_PASSWORD=${N8N_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_PORT=${N8N_PORT}

  nginx:
    env_file:
      - .env.development
    environment:

