version: '3.8'

services:
  protocol-integration:
    build:
      context: ./services/protocol-integration
      dockerfile: Dockerfile
    container_name: protocol-integration
    ports:
      - "3005:3005"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - AI_AGENTS_URL=http://ai-agents:3000
      - IDE_BRIDGE_URL=http://ide-bridge:3004
      - N8N_URL=http://n8n:5678
      - LSP_PORT=3000
      - MCP_PORT=3001
      - REST_PORT=3002
      - GRAPHQL_PORT=3003
      - WEBSOCKET_PORT=3004
    volumes:
      - ./services/protocol-integration:/app
      - protocol-integration-logs:/app/logs
    networks:
      - multimodal-llm-stack
    restart: unless-stopped
    depends_on:
      - ai-agents
      - ide-bridge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  protocol-integration-logs:

networks:
  multimodal-llm-stack:
    external: true