# IDE Bridge Service Docker Compose Configuration
# Extends the main docker-compose.yml

services:
  # IDE Bridge Service
  ide-bridge:
    build:
      context: ./services/ide-bridge
      dockerfile: Dockerfile
    container_name: multimodal-ide-bridge
    ports:
      - "8007:8007"
    environment:
      - IDE_BRIDGE_HOST=0.0.0.0
      - IDE_BRIDGE_PORT=8007
      - DEBUG=${DEBUG:-false}
      
      # LSP Configuration
      - LSP_MAX_CONNECTIONS=100
      - LSP_TIMEOUT=30
      - LSP_ENABLED=true
      
      # MCP Configuration
      - MCP_ENABLED=true
      - MCP_TOOLS_PATH=/app/tools
      - MCP_MAX_TOOLS=50
      
      # WebSocket Configuration
      - WS_MAX_CONNECTIONS=50
      - WS_HEARTBEAT_INTERVAL=30
      - WS_ENABLED=true
      
      # Agent Integration
      - AI_AGENTS_URL=http://ai-agents:8003
      - AGENT_TIMEOUT=60
      - AGENT_ENABLED=true
      
      # Code Analysis
      - CODE_ANALYSIS_ENABLED=true
      - SUPPORTED_LANGUAGES=python,javascript,typescript,go,rust,java,cpp,c
      
      # Database Configuration
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-multimodal}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      
      # Redis Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=6
      
      # Security
      - SECRET_KEY=${IDE_BRIDGE_SECRET_KEY:-ide-bridge-secret-key}
      - ALLOWED_ORIGINS=*
      
      # Performance
      - MAX_REQUEST_SIZE=10485760
      - REQUEST_TIMEOUT=30
      
      # Logging
      - LOG_LEVEL=INFO
    volumes:
      - ide_bridge_cache:/app/cache
      - ./services/ide-bridge/tools:/app/tools:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ai-agents:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - multimodal-net

  # IDE Bridge Web Interface (Optional)
  ide-bridge-web:
    build:
      context: ./services/ide-bridge/web
      dockerfile: Dockerfile
    container_name: multimodal-ide-bridge-web
    ports:
      - "3002:3000"
    environment:
      - REACT_APP_IDE_BRIDGE_URL=http://localhost:8007
      - REACT_APP_WS_URL=ws://localhost:8007/ws
    depends_on:
      ide-bridge:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - multimodal-net

volumes:
  ide_bridge_cache:
    driver: local

networks:
  multimodal-net:
    external: true