blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/your-org/llm-multimodal-stack/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/your-org/llm-multimodal-stack/tree/main/docs
    about: Check our comprehensive documentation
  - name: 🆘 Troubleshooting Guide
    url: https://github.com/your-org/llm-multimodal-stack/blob/main/docs/troubleshooting.md
    about: Common issues and solutions
