cluster.name: multimodal-cluster
node.name: multimodal-node-1
node.roles: [ master, data, ingest ]

path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

network.host: 0.0.0.0
http.port: 9200

discovery.type: single-node

# Memory settings
bootstrap.memory_lock: true

# Security settings
xpack.security.enabled: false
xpack.security.enrollment.enabled: false

# Performance settings
indices.memory.index_buffer_size: 20%
indices.queries.cache.size: 10%
indices.fielddata.cache.size: 20%

# Logging settings
logger.level: INFO
