model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_base: http://vllm:8000/v1
      api_key: dummy-key
      
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4
      api_base: http://vllm:8000/v1
      api_key: dummy-key

router_settings:
  routing_strategy: simple-shuffle

litellm_settings:
  drop_params: true
  set_verbose: false
  json_logs: true

# Disable database for now - use in-memory only
general_settings:
  completion_model: gpt-3.5-turbo
