model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_base: http://vllm:8000/v1
      api_key: dummy-key
      
  - model_name: local-llm
    litellm_params:
      model: openai/local-model
      api_base: http://vllm:8000/v1
      api_key: dummy-key

router_settings:
  routing_strategy: simple-shuffle
  model_group_alias:
    gpt-3.5-turbo: local-llm

litellm_settings:
  drop_params: true
  set_verbose: false
  json_logs: true

general_settings:
  completion_model: local-llm
  master_key: sk-Y/JfF3FLgezDRjqjUhFQGJVMYYLOE0DgDxnPyp4RLhQ=
  database_url: postgresql://postgres:v1gg6iFZdfgQN25ucFvB9WKrgARE3aXS+Y3rq6Fa6OA=@postgres:5432/multimodal
