model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/microsoft/DialoGPT-medium
      api_base: http://vllm:8000/v1
      api_key: ${VLLM_API_KEY:-dummy-key}
      
  - model_name: gpt-4
    litellm_params:
      model: openai/microsoft/DialoGPT-medium
      api_base: http://vllm:8000/v1
      api_key: ${VLLM_API_KEY:-dummy-key}

router_settings:
  routing_strategy: simple-shuffle

litellm_settings:
  drop_params: true
  set_verbose: false
  json_logs: true
  master_key: ${LITELLM_MASTER_KEY}

# Authentication and general settings
general_settings:
  completion_model: gpt-3.5-turbo
  master_key: ${LITELLM_MASTER_KEY}
