global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'multimodal-production'
    environment: 'production'

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /nginx_status

  - job_name: 'multimodal-worker'
    static_configs:
      - targets: ['multimodal-worker:8001']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'retrieval-proxy'
    static_configs:
      - targets: ['retrieval-proxy:8002']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'litellm'
    static_configs:
      - targets: ['litellm:4000']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'vllm'
    static_configs:
      - targets: ['vllm:8000']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 30s
    metrics_path: /_prometheus/metrics

  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash:9600']
    scrape_interval: 30s
    metrics_path: /_node/stats/prometheus

  - job_name: 'kibana'
    static_configs:
      - targets: ['kibana:5601']
    scrape_interval: 30s
    metrics_path: /api/status

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
