backup_before_rotation: true
notification_channels:
  email: ${ALERT_EMAIL}
  slack: ${SLACK_WEBHOOK_URL}
rollback_on_failure: true
rotation_policies:
  api_keys: 180
  database_passwords: 90
  encryption_keys: 365
  jwt_secrets: 30
rotation_schedule:
  api_keys: 0 3 1 * *
  database_passwords: 0 2 * * 0
  encryption_keys: 0 5 1 1 *
  jwt_secrets: 0 4 * * 1
