# Test Metrics Dashboard Configuration
# Generated on: 2025-09-29T10:27:54.022869

metrics:
  # Test execution metrics
  execution:
    - name: "Test Execution Time"
      type: "duration"
      unit: "seconds"
      aggregation: "average"
    
    - name: "Test Success Rate"
      type: "percentage"
      unit: "percent"
      aggregation: "average"
    
    - name: "Test Failure Rate"
      type: "percentage"
      unit: "percent"
      aggregation: "average"
    
    - name: "Test Coverage"
      type: "percentage"
      unit: "percent"
      aggregation: "average"
  
  # Performance metrics
  performance:
    - name: "API Response Time"
      type: "duration"
      unit: "milliseconds"
      aggregation: "percentile_95"
    
    - name: "Database Query Time"
      type: "duration"
      unit: "milliseconds"
      aggregation: "percentile_95"
    
    - name: "Memory Usage"
      type: "memory"
      unit: "MB"
      aggregation: "peak"
    
    - name: "CPU Usage"
      type: "percentage"
      unit: "percent"
      aggregation: "peak"
  
  # Quality metrics
  quality:
    - name: "Code Quality Score"
      type: "score"
      unit: "points"
      aggregation: "average"
    
    - name: "Security Score"
      type: "score"
      unit: "points"
      aggregation: "average"
    
    - name: "Maintainability Index"
      type: "index"
      unit: "points"
      aggregation: "average"

# Dashboard configuration
dashboard:
  title: "LLM Multimodal Stack Test Metrics"
  refresh_interval: "30s"
  time_range: "24h"
  
  # Widgets
  widgets:
    - title: "Test Execution Summary"
      type: "summary"
      metrics:
        - "Test Success Rate"
        - "Test Failure Rate"
        - "Test Coverage"
    
    - title: "Performance Trends"
      type: "line_chart"
      metrics:
        - "API Response Time"
        - "Database Query Time"
        - "Memory Usage"
    
    - title: "Quality Metrics"
      type: "gauge"
      metrics:
        - "Code Quality Score"
        - "Security Score"
        - "Maintainability Index"
    
    - title: "Test Categories"
      type: "pie_chart"
      metrics:
        - "Unit Tests"
        - "Integration Tests"
        - "Performance Tests"
        - "E2E Tests"

# Alerting configuration
alerting:
  rules:
    - name: "High Test Failure Rate"
      condition: "Test Failure Rate > 10%"
      severity: "warning"
      duration: "5m"
    
    - name: "Low Test Coverage"
      condition: "Test Coverage < 80%"
      severity: "warning"
      duration: "10m"
    
    - name: "High API Response Time"
      condition: "API Response Time > 2000ms"
      severity: "critical"
      duration: "2m"
    
    - name: "High Memory Usage"
      condition: "Memory Usage > 8GB"
      severity: "warning"
      duration: "5m"

# Reporting configuration
reporting:
  # Report types
  types:
    - name: "Daily Test Report"
      schedule: "0 8 * * *"
      recipients: ["team@example.com"]
      format: "html"
    
    - name: "Weekly Quality Report"
      schedule: "0 9 * * 1"
      recipients: ["management@example.com"]
      format: "pdf"
    
    - name: "Performance Report"
      schedule: "0 10 * * 1"
      recipients: ["performance@example.com"]
      format: "html"
  
  # Report templates
  templates:
    daily:
      title: "Daily Test Execution Report"
      sections:
        - "Test Summary"
        - "Failed Tests"
        - "Performance Metrics"
        - "Recommendations"
    
    weekly:
      title: "Weekly Quality Report"
      sections:
        - "Quality Trends"
        - "Coverage Analysis"
        - "Performance Analysis"
        - "Action Items"
